import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const supportedLanguages = ['es', 'en', 'fr', 'it'] as const;
export type SupportedLanguage = (typeof supportedLanguages)[number];

const LANGUAGE_STORAGE_KEY = 'omiki-language-preference';
const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
const initialLanguage = supportedLanguages.includes(storedLanguage as SupportedLanguage)
  ? storedLanguage as SupportedLanguage
  : 'es';

const resources = {
  es: { translation: {
    language: { label: 'Idioma', es: 'Castellano', en: 'Inglés', fr: 'Francés', it: 'Italiano' },
    common: { share: 'Compartir la app', notifications: 'Avisos', signIn: 'Entrar', profile: 'Mi perfil', openProfile: 'Abrir Mi perfil', user: 'usuario', back: 'Volver a la pantalla anterior', home: 'Volver al inicio', logout: 'Cerrar sesión', reload: 'Recargar página', cancel: 'Cancelar', accept: 'Aceptar', close: 'Cerrar' },
    activity: { panelTitle: 'Mensajes y notificaciones', title: 'Actividad de juego', empty: 'Todavía no hay avisos en esta partida.', hole: 'Hoyo {{number}}', loadError: 'No se pudo cargar la actividad de juego.', events: { hole_in_one: 'Hoyo en uno', no_paso_rojas: 'No pasó de rojas', spanish_hands: 'Spanish Hands' } },
    access: { title: 'Código de acceso', description: 'Introduce el código de acceso para unirte o editar esta partida.', placeholder: 'Código', hint: 'Código de 4 caracteres', verifying: 'Verificando…', enter: 'Acceder', footer: 'El código lo proporciona el creador de la partida. Todas las clasificaciones son públicas.' },
    share: { title: '¡Únete a Omiki Golf!', text: '¡Lleva el control de tus partidas de golf con amigos!', description: 'Comparte con tus amigos para empezar la partida', scan: 'Escanea con la cámara del móvil para abrir la app', native: 'Compartir (WhatsApp, aplicaciones…)', showQr: 'Mostrar código QR', copyLink: 'Copiar enlace' },
    home: { tagline: 'Tu compañero de golf', createExpress: 'Crear Partida Express', createGame: 'Crear Partida', joinGame: 'Unirse a Partida', createTeam: 'Crear Team', simulator: 'Simulador', plan: 'Plan: {{plan}}', preview: 'Viendo la app como {{user}} con plan {{plan}}' },
    theme: { light: 'Cambiar a tema claro', dark: 'Cambiar a tema oscuro' },
    errorBoundary: { title: 'Algo salió mal', message: 'La aplicación encontró un error inesperado.', details: 'Detalles técnicos' },
    auth: { login: 'Iniciar sesión', loggingIn: 'Iniciando sesión…', loginSubtitle: 'Accede a tus grupos guardados', identifier: 'Correo o usuario administrador', identifierPlaceholder: 'Correo o AdminF', password: 'Contraseña', forgot: '¿Olvidaste tu contraseña?', noAccount: '¿No tienes cuenta?', registerLink: 'Regístrate', plans: 'Ver planes', createAccount: 'Crear cuenta', creatingAccount: 'Creando cuenta…', registerSubtitle: 'Guarda tus grupos y accede desde cualquier dispositivo', name: 'Nombre', namePlaceholder: 'Tu nombre', nick: 'Nick único', nickPlaceholder: 'Tu nombre dentro de Omiki', checkingNick: 'Comprobando disponibilidad…', nickAvailable: 'Nick disponible', nickTaken: 'Este nick no está disponible.', useNick: 'Usar {{nick}}', avatar: 'Avatar', selectAvatar: 'Seleccionar {{name}}', email: 'Correo electrónico', minPassword: 'Mínimo 6 caracteres', confirmPassword: 'Confirmar contraseña', repeatPassword: 'Repite tu contraseña', userType: 'Tipo de usuario', hasAccount: '¿Ya tienes cuenta?', resetTitle: 'Nueva contraseña', resetSubtitle: 'Introduce tu nueva contraseña', confirmNewPassword: 'Confirmar nueva contraseña', updating: 'Actualizando…', updatePassword: 'Actualizar contraseña', recoverTitle: 'Recuperar contraseña', recoverSubtitle: 'Te enviaremos un enlace para restablecer tu contraseña', sending: 'Enviando…', sendRecovery: 'Enviar enlace de recuperación', errors: { nickCheck: 'No se ha podido comprobar el nick. Inténtalo de nuevo.', login: 'Error al iniciar sesión', passwords: 'Las contraseñas no coinciden', passwordLength: 'La contraseña debe tener al menos 6 caracteres', name: 'Introduce tu nombre', nick: 'Elige un nick disponible', register: 'Error al registrarse', recovery: 'Error al enviar el correo de recuperación', update: 'Error al actualizar la contraseña' }, messages: { accountCreated: 'Cuenta creada correctamente. Iniciando sesión…', recoverySent: 'Se ha enviado un enlace de recuperación a tu correo electrónico.', passwordUpdated: 'Contraseña actualizada correctamente. Redirigiendo…' } },
    profile: { player: 'Jugador', rounds: 'Mis partidas jugadas', stats: 'Mis estadísticas', groups: 'Mis grupos', details: 'Mis datos de registro', supportId: 'ID de soporte', supportIdHelp: 'Envíanos este identificador si necesitas ayuda con tu cuenta.', copySupportId: 'Copiar', copiedSupportId: 'Copiado', trial: 'Prueba Team durante 30 días', trialDescription: 'Crea grupos, invita jugadores y mucho más', detailsDescription: 'Personaliza cómo te ven los demás jugadores.', legacy: 'Tu cuenta es anterior a los nuevos perfiles. Completa estos datos una sola vez para crear el tuyo.', nickLocked: 'El nick no se puede modificar por ahora.', saved: 'Cambios guardados.', saving: 'Guardando…', save: 'Guardar cambios', create: 'Crear mi perfil', saveError: 'No se han podido guardar los datos. Comprueba el nick e inténtalo de nuevo.' },
    groups: { title: 'Mis grupos', loading: 'Cargando tus grupos…', noSession: 'No hay sesión activa', loadError: 'Error al cargar los grupos', deleteError: 'Error al eliminar el grupo', premium: 'Hazte Premium', premiumActive: 'Premium activo', empty: 'Aún no has creado ningún grupo', delete: 'Eliminar grupo', accessCode: 'Código de acceso', copyCode: 'Copiar código', copied: 'Copiado', copy: 'Copiar', select: 'Seleccionar grupo', created: 'Creado el {{date}}', deleteConfirm: '¿Estás seguro de que quieres eliminar este grupo? Esta acción no se puede deshacer.' },
    roundSetup: { quick: 'Partida rápida', manager: 'Gestor de partidas y puntuación', express: 'Modo Express', remaining: 'Te quedan {{remaining}} de {{total}} partidas disponibles en esta modalidad.', played: 'Llevas {{count}} partidas', groupCode: 'Código del grupo', leaveGroup: 'Salir del grupo', leave: 'Salir', shareCode: 'Comparte este código con otros para que puedan participar en las partidas del grupo:', group: 'Grupo: {{name}}', joinTitle: 'Unirse con código a una partida', joinDescription: '¿Tienes un código de acceso? Úsalo para unirte a una partida existente y editar las puntuaciones.', enterCode: 'Introducir código', newRound: 'Nueva partida', selectCourse: 'Selecciona un campo', coursePlaceholder: '-- Selecciona un campo --', holes: 'Número de hoyos', holesCount: '{{count}} hoyos', handicap: 'Cálculo de hándicap', withSlope: 'Con Slope', withoutSlope: 'Sin Slope', selectTee: 'Selecciona barras', gameMode: 'Modalidad de juego', matchHelp: '2 jugadores. Se gana por hoyo, no por puntos.', sindicatoHelp: '3 jugadores. 6 puntos por hoyo: 4/2/0, 3/3/0 o 4/1/1.', pairsHelp: '2 parejas de 2 jugadores (4 en total).', create: 'Crear partida', active: 'Partidas activas', myRound: 'Mi partida', activeDescription: 'Edita las partidas y observa en tiempo real las puntuaciones de todas las partidas activas.', myRoundDescription: 'Accede a tu partida rápida activa y continúa donde lo dejaste.', viewRound: 'Ver partida', statistics: 'Estadísticas', viewStatistics: 'Ver estadísticas', statsAvailable: 'Consulta los premios y estadísticas del historial de partidas.', statsEmpty: 'No hay partidas completadas o archivadas para mostrar.', points: 'Puntos de juego', viewPoints: 'Ver puntos', errors: { courses: 'Error al cargar los campos de golf', expressLimit: 'Has alcanzado el límite máximo de 4 partidas del plan Express.', active: 'Tienes una partida en curso. Finalízala y archívala desde Mi partida antes de crear una nueva.', archive: 'Tienes una partida finalizada pendiente de archivar. Ve a Mi partida para archivarla antes de crear una nueva.', selectCourse: 'Selecciona un campo.', create: 'Error al crear la partida', pin: 'PIN incorrecto. Inténtalo de nuevo.' } },
  } },
  en: { translation: {
    language: { label: 'Language', es: 'Spanish', en: 'English', fr: 'French', it: 'Italian' },
    common: { share: 'Share the app', notifications: 'Notifications', signIn: 'Sign in', profile: 'My profile', openProfile: 'Open my profile', user: 'user', back: 'Go back', home: 'Back to home', logout: 'Sign out', reload: 'Reload page', cancel: 'Cancel', accept: 'Accept', close: 'Close' },
    activity: { panelTitle: 'Messages and notifications', title: 'Game activity', empty: 'There are no game alerts yet.', hole: 'Hole {{number}}', loadError: 'Could not load game activity.', events: { hole_in_one: 'Hole in one', no_paso_rojas: 'Did not pass the red tees', spanish_hands: 'Spanish Hands' } },
    access: { title: 'Access code', description: 'Enter the access code to join or edit this round.', placeholder: 'Code', hint: '4-character code', verifying: 'Checking…', enter: 'Enter', footer: 'The access code is provided by the round creator. All leaderboards are public.' },
    share: { title: 'Join Omiki Golf!', text: 'Keep track of your golf rounds with friends!', description: 'Share with your friends to start the round', scan: 'Scan with your phone camera to open the app', native: 'Share (WhatsApp, apps…)', showQr: 'Show QR code', copyLink: 'Copy link' },
    home: { tagline: 'Your golf companion', createExpress: 'Create Express Round', createGame: 'Create Round', joinGame: 'Join Round', createTeam: 'Create Team', simulator: 'Simulator', plan: 'Plan: {{plan}}', preview: 'Viewing the app as {{user}} on the {{plan}} plan' },
    theme: { light: 'Switch to light theme', dark: 'Switch to dark theme' },
    errorBoundary: { title: 'Something went wrong', message: 'The application encountered an unexpected error.', details: 'Technical details' },
    auth: { login: 'Sign in', loggingIn: 'Signing in…', loginSubtitle: 'Access your saved groups', identifier: 'Email or administrator username', identifierPlaceholder: 'Email or AdminF', password: 'Password', forgot: 'Forgot your password?', noAccount: "Don't have an account?", registerLink: 'Sign up', plans: 'View plans', createAccount: 'Create account', creatingAccount: 'Creating account…', registerSubtitle: 'Save your groups and access them from any device', name: 'Name', namePlaceholder: 'Your name', nick: 'Unique nickname', nickPlaceholder: 'Your name in Omiki', checkingNick: 'Checking availability…', nickAvailable: 'Nickname available', nickTaken: 'This nickname is not available.', useNick: 'Use {{nick}}', avatar: 'Avatar', selectAvatar: 'Select {{name}}', email: 'Email', minPassword: 'At least 6 characters', confirmPassword: 'Confirm password', repeatPassword: 'Repeat your password', userType: 'User type', hasAccount: 'Already have an account?', resetTitle: 'New password', resetSubtitle: 'Enter your new password', confirmNewPassword: 'Confirm new password', updating: 'Updating…', updatePassword: 'Update password', recoverTitle: 'Recover password', recoverSubtitle: 'We will send you a link to reset your password', sending: 'Sending…', sendRecovery: 'Send recovery link', errors: { nickCheck: 'Could not check the nickname. Please try again.', login: 'Could not sign in', passwords: 'Passwords do not match', passwordLength: 'Password must be at least 6 characters', name: 'Enter your name', nick: 'Choose an available nickname', register: 'Could not create the account', recovery: 'Could not send the recovery email', update: 'Could not update the password' }, messages: { accountCreated: 'Account created successfully. Signing in…', recoverySent: 'A recovery link has been sent to your email.', passwordUpdated: 'Password updated successfully. Redirecting…' } },
    profile: { player: 'Player', rounds: 'My rounds', stats: 'My statistics', groups: 'My groups', details: 'My registration details', supportId: 'Support ID', supportIdHelp: 'Send us this identifier if you need help with your account.', copySupportId: 'Copy', copiedSupportId: 'Copied', trial: 'Try Team for 30 days', trialDescription: 'Create groups, invite players and much more', detailsDescription: 'Customise how other players see you.', legacy: 'Your account predates the new profiles. Complete these details once to create yours.', nickLocked: 'The nickname cannot currently be changed.', saved: 'Changes saved.', saving: 'Saving…', save: 'Save changes', create: 'Create my profile', saveError: 'Could not save your details. Check the nickname and try again.' },
    groups: { title: 'My groups', loading: 'Loading your groups…', noSession: 'There is no active session', loadError: 'Could not load groups', deleteError: 'Could not delete the group', premium: 'Go Premium', premiumActive: 'Premium active', empty: 'You have not created any groups yet', delete: 'Delete group', accessCode: 'Access code', copyCode: 'Copy code', copied: 'Copied', copy: 'Copy', select: 'Select group', created: 'Created on {{date}}', deleteConfirm: 'Are you sure you want to delete this group? This action cannot be undone.' },
    roundSetup: { quick: 'Quick round', manager: 'Round and scoring manager', express: 'Express mode', remaining: '{{remaining}} of {{total}} rounds remaining in this mode.', played: 'You have played {{count}} rounds', groupCode: 'Group code', leaveGroup: 'Leave group', leave: 'Leave', shareCode: 'Share this code so others can participate in the group’s rounds:', group: 'Group: {{name}}', joinTitle: 'Join a round with a code', joinDescription: 'Have an access code? Use it to join an existing round and edit scores.', enterCode: 'Enter code', newRound: 'New round', selectCourse: 'Select a course', coursePlaceholder: '-- Select a course --', holes: 'Number of holes', holesCount: '{{count}} holes', handicap: 'Handicap calculation', withSlope: 'With Slope', withoutSlope: 'Without Slope', selectTee: 'Select tees', gameMode: 'Game mode', matchHelp: '2 players. Win by hole, not by points.', sindicatoHelp: '3 players. 6 points per hole: 4/2/0, 3/3/0 or 4/1/1.', pairsHelp: '2 pairs of 2 players (4 total).', create: 'Create round', active: 'Active rounds', myRound: 'My round', activeDescription: 'Edit rounds and follow every active round’s scores in real time.', myRoundDescription: 'Open your active quick round and continue where you left off.', viewRound: 'View round', statistics: 'Statistics', viewStatistics: 'View statistics', statsAvailable: 'View awards and statistics from your round history.', statsEmpty: 'There are no completed or archived rounds to show.', points: 'Game points', viewPoints: 'View points', errors: { courses: 'Could not load golf courses', expressLimit: 'You have reached the 4-round limit for the Express plan.', active: 'You have a round in progress. Finish or delete it before creating another.', archive: 'You have a completed round waiting to be archived. Archive it in My rounds before creating another.', selectCourse: 'Select a course.', create: 'Could not create the round', pin: 'Incorrect PIN. Try again.' } },
  } },
  fr: { translation: {
    language: { label: 'Langue', es: 'Espagnol', en: 'Anglais', fr: 'Français', it: 'Italien' },
    common: { share: "Partager l’application", notifications: 'Notifications', signIn: 'Se connecter', profile: 'Mon profil', openProfile: 'Ouvrir mon profil', user: 'utilisateur', back: 'Revenir en arrière', home: 'Retour à l’accueil', logout: 'Se déconnecter', reload: 'Recharger la page', cancel: 'Annuler', accept: 'Accepter', close: 'Fermer' },
    activity: { panelTitle: 'Messages et notifications', title: 'Activité de jeu', empty: 'Il n’y a pas encore d’alertes de jeu.', hole: 'Trou {{number}}', loadError: 'Impossible de charger l’activité de jeu.', events: { hole_in_one: 'Trou en un', no_paso_rojas: 'N’a pas dépassé les départs rouges', spanish_hands: 'Spanish Hands' } },
    access: { title: 'Code d’accès', description: 'Saisissez le code pour rejoindre ou modifier cette partie.', placeholder: 'Code', hint: 'Code à 4 caractères', verifying: 'Vérification…', enter: 'Accéder', footer: 'Le code est fourni par le créateur de la partie. Tous les classements sont publics.' },
    share: { title: 'Rejoignez Omiki Golf !', text: 'Suivez vos parties de golf entre amis !', description: 'Partagez avec vos amis pour commencer la partie', scan: 'Scannez avec l’appareil photo du téléphone pour ouvrir l’application', native: 'Partager (WhatsApp, applications…)', showQr: 'Afficher le code QR', copyLink: 'Copier le lien' },
    home: { tagline: 'Votre compagnon de golf', createExpress: 'Créer une partie Express', createGame: 'Créer une partie', joinGame: 'Rejoindre une partie', createTeam: 'Créer une équipe', simulator: 'Simulateur', plan: 'Formule : {{plan}}', preview: "Aperçu de l’application pour {{user}} avec la formule {{plan}}" },
    theme: { light: 'Passer au thème clair', dark: 'Passer au thème sombre' },
    errorBoundary: { title: 'Une erreur est survenue', message: "L’application a rencontré une erreur inattendue.", details: 'Détails techniques' },
    auth: { login: 'Se connecter', loggingIn: 'Connexion…', loginSubtitle: 'Accédez à vos groupes enregistrés', identifier: 'E-mail ou identifiant administrateur', identifierPlaceholder: 'E-mail ou AdminF', password: 'Mot de passe', forgot: 'Mot de passe oublié ?', noAccount: 'Vous n’avez pas de compte ?', registerLink: 'Inscrivez-vous', plans: 'Voir les formules', createAccount: 'Créer un compte', creatingAccount: 'Création du compte…', registerSubtitle: 'Enregistrez vos groupes et retrouvez-les sur tous vos appareils', name: 'Nom', namePlaceholder: 'Votre nom', nick: 'Pseudo unique', nickPlaceholder: 'Votre nom dans Omiki', checkingNick: 'Vérification…', nickAvailable: 'Pseudo disponible', nickTaken: 'Ce pseudo n’est pas disponible.', useNick: 'Utiliser {{nick}}', avatar: 'Avatar', selectAvatar: 'Sélectionner {{name}}', email: 'E-mail', minPassword: '6 caractères minimum', confirmPassword: 'Confirmer le mot de passe', repeatPassword: 'Répétez votre mot de passe', userType: 'Type d’utilisateur', hasAccount: 'Vous avez déjà un compte ?', resetTitle: 'Nouveau mot de passe', resetSubtitle: 'Saisissez votre nouveau mot de passe', confirmNewPassword: 'Confirmer le nouveau mot de passe', updating: 'Mise à jour…', updatePassword: 'Mettre à jour le mot de passe', recoverTitle: 'Récupérer le mot de passe', recoverSubtitle: 'Nous vous enverrons un lien pour réinitialiser votre mot de passe', sending: 'Envoi…', sendRecovery: 'Envoyer le lien de récupération', errors: { nickCheck: 'Impossible de vérifier le pseudo. Réessayez.', login: 'Erreur de connexion', passwords: 'Les mots de passe ne correspondent pas', passwordLength: 'Le mot de passe doit comporter au moins 6 caractères', name: 'Saisissez votre nom', nick: 'Choisissez un pseudo disponible', register: 'Erreur lors de la création du compte', recovery: 'Erreur lors de l’envoi de l’e-mail', update: 'Erreur lors de la mise à jour du mot de passe' }, messages: { accountCreated: 'Compte créé. Connexion en cours…', recoverySent: 'Un lien de récupération a été envoyé à votre adresse e-mail.', passwordUpdated: 'Mot de passe mis à jour. Redirection…' } },
    profile: { player: 'Joueur', rounds: 'Mes parties jouées', stats: 'Mes statistiques', groups: 'Mes groupes', details: 'Mes données d’inscription', supportId: 'Identifiant d’assistance', supportIdHelp: 'Envoyez-nous cet identifiant si vous avez besoin d’aide avec votre compte.', copySupportId: 'Copier', copiedSupportId: 'Copié', trial: 'Essayez Team pendant 30 jours', trialDescription: 'Créez des groupes, invitez des joueurs et bien plus encore', detailsDescription: 'Personnalisez la façon dont les autres joueurs vous voient.', legacy: 'Votre compte est antérieur aux nouveaux profils. Complétez ces informations une fois pour créer le vôtre.', nickLocked: 'Le pseudo ne peut pas être modifié pour le moment.', saved: 'Modifications enregistrées.', saving: 'Enregistrement…', save: 'Enregistrer les modifications', create: 'Créer mon profil', saveError: 'Impossible d’enregistrer les données. Vérifiez le pseudo et réessayez.' },
    groups: { title: 'Mes groupes', loading: 'Chargement de vos groupes…', noSession: 'Aucune session active', loadError: 'Impossible de charger les groupes', deleteError: 'Impossible de supprimer le groupe', premium: 'Passer à Premium', premiumActive: 'Premium actif', empty: 'Vous n’avez encore créé aucun groupe', delete: 'Supprimer le groupe', accessCode: 'Code d’accès', copyCode: 'Copier le code', copied: 'Copié', copy: 'Copier', select: 'Sélectionner le groupe', created: 'Créé le {{date}}', deleteConfirm: 'Voulez-vous vraiment supprimer ce groupe ? Cette action est irréversible.' },
    roundSetup: { quick: 'Partie rapide', manager: 'Gestionnaire de parties et de scores', express: 'Mode Express', remaining: 'Il vous reste {{remaining}} parties sur {{total}} dans ce mode.', played: 'Vous avez joué {{count}} parties', groupCode: 'Code du groupe', leaveGroup: 'Quitter le groupe', leave: 'Quitter', shareCode: 'Partagez ce code pour permettre aux autres de participer aux parties du groupe :', group: 'Groupe : {{name}}', joinTitle: 'Rejoindre une partie avec un code', joinDescription: 'Vous avez un code d’accès ? Utilisez-le pour rejoindre une partie et modifier les scores.', enterCode: 'Saisir le code', newRound: 'Nouvelle partie', selectCourse: 'Sélectionnez un parcours', coursePlaceholder: '-- Sélectionnez un parcours --', holes: 'Nombre de trous', holesCount: '{{count}} trous', handicap: 'Calcul du handicap', withSlope: 'Avec Slope', withoutSlope: 'Sans Slope', selectTee: 'Sélectionnez les départs', gameMode: 'Mode de jeu', matchHelp: '2 joueurs. La victoire se joue par trou, pas aux points.', sindicatoHelp: '3 joueurs. 6 points par trou : 4/2/0, 3/3/0 ou 4/1/1.', pairsHelp: '2 équipes de 2 joueurs (4 au total).', create: 'Créer la partie', active: 'Parties actives', myRound: 'Ma partie', activeDescription: 'Modifiez les parties et suivez les scores de toutes les parties actives en temps réel.', myRoundDescription: 'Ouvrez votre partie rapide active et reprenez là où vous vous étiez arrêté.', viewRound: 'Voir la partie', statistics: 'Statistiques', viewStatistics: 'Voir les statistiques', statsAvailable: 'Consultez les récompenses et statistiques de votre historique.', statsEmpty: 'Aucune partie terminée ou archivée à afficher.', points: 'Points de jeu', viewPoints: 'Voir les points', errors: { courses: 'Impossible de charger les parcours', expressLimit: 'Vous avez atteint la limite de 4 parties du forfait Express.', active: 'Une partie est en cours. Terminez-la ou supprimez-la avant d’en créer une autre.', archive: 'Une partie terminée doit être archivée. Archivez-la dans Mes parties avant d’en créer une autre.', selectCourse: 'Sélectionnez un parcours.', create: 'Impossible de créer la partie', pin: 'PIN incorrect. Réessayez.' } },
  } },
  it: { translation: {
    language: { label: 'Lingua', es: 'Spagnolo', en: 'Inglese', fr: 'Francese', it: 'Italiano' },
    common: { share: "Condividi l’app", notifications: 'Notifiche', signIn: 'Accedi', profile: 'Il mio profilo', openProfile: 'Apri il mio profilo', user: 'utente', back: 'Torna indietro', home: 'Torna alla home', logout: 'Esci', reload: 'Ricarica pagina', cancel: 'Annulla', accept: 'Accetta', close: 'Chiudi' },
    activity: { panelTitle: 'Messaggi e notifiche', title: 'Attività di gioco', empty: 'Non ci sono ancora avvisi di gioco.', hole: 'Buca {{number}}', loadError: 'Impossibile caricare l’attività di gioco.', events: { hole_in_one: 'Buca in uno', no_paso_rojas: 'Non ha superato i tee rossi', spanish_hands: 'Spanish Hands' } },
    access: { title: 'Codice di accesso', description: 'Inserisci il codice per unirti o modificare questa partita.', placeholder: 'Codice', hint: 'Codice di 4 caratteri', verifying: 'Verifica…', enter: 'Accedi', footer: 'Il codice è fornito dal creatore della partita. Tutte le classifiche sono pubbliche.' },
    share: { title: 'Unisciti a Omiki Golf!', text: 'Tieni sotto controllo le partite di golf con gli amici!', description: 'Condividi con i tuoi amici per iniziare la partita', scan: 'Scansiona con la fotocamera del telefono per aprire l’app', native: 'Condividi (WhatsApp, app…)', showQr: 'Mostra codice QR', copyLink: 'Copia link' },
    home: { tagline: 'Il tuo compagno di golf', createExpress: 'Crea Partita Express', createGame: 'Crea Partita', joinGame: 'Unisciti alla Partita', createTeam: 'Crea Team', simulator: 'Simulatore', plan: 'Piano: {{plan}}', preview: "Visualizzazione dell’app come {{user}} con il piano {{plan}}" },
    theme: { light: 'Passa al tema chiaro', dark: 'Passa al tema scuro' },
    errorBoundary: { title: 'Si è verificato un errore', message: "L’applicazione ha riscontrato un errore imprevisto.", details: 'Dettagli tecnici' },
    auth: { login: 'Accedi', loggingIn: 'Accesso…', loginSubtitle: 'Accedi ai gruppi salvati', identifier: 'E-mail o nome amministratore', identifierPlaceholder: 'E-mail o AdminF', password: 'Password', forgot: 'Hai dimenticato la password?', noAccount: 'Non hai un account?', registerLink: 'Registrati', plans: 'Vedi piani', createAccount: 'Crea account', creatingAccount: 'Creazione account…', registerSubtitle: 'Salva i tuoi gruppi e accedi da qualsiasi dispositivo', name: 'Nome', namePlaceholder: 'Il tuo nome', nick: 'Nickname univoco', nickPlaceholder: 'Il tuo nome in Omiki', checkingNick: 'Verifica disponibilità…', nickAvailable: 'Nickname disponibile', nickTaken: 'Questo nickname non è disponibile.', useNick: 'Usa {{nick}}', avatar: 'Avatar', selectAvatar: 'Seleziona {{name}}', email: 'E-mail', minPassword: 'Minimo 6 caratteri', confirmPassword: 'Conferma password', repeatPassword: 'Ripeti la password', userType: 'Tipo di utente', hasAccount: 'Hai già un account?', resetTitle: 'Nuova password', resetSubtitle: 'Inserisci la nuova password', confirmNewPassword: 'Conferma nuova password', updating: 'Aggiornamento…', updatePassword: 'Aggiorna password', recoverTitle: 'Recupera password', recoverSubtitle: 'Ti invieremo un link per reimpostare la password', sending: 'Invio…', sendRecovery: 'Invia link di recupero', errors: { nickCheck: 'Impossibile verificare il nickname. Riprova.', login: 'Errore durante l’accesso', passwords: 'Le password non corrispondono', passwordLength: 'La password deve contenere almeno 6 caratteri', name: 'Inserisci il tuo nome', nick: 'Scegli un nickname disponibile', register: 'Errore durante la registrazione', recovery: 'Errore durante l’invio dell’e-mail', update: 'Errore durante l’aggiornamento della password' }, messages: { accountCreated: 'Account creato. Accesso in corso…', recoverySent: 'È stato inviato un link di recupero al tuo indirizzo e-mail.', passwordUpdated: 'Password aggiornata. Reindirizzamento…' } },
    profile: { player: 'Giocatore', rounds: 'Le mie partite', stats: 'Le mie statistiche', groups: 'I miei gruppi', details: 'I miei dati di registrazione', supportId: 'ID assistenza', supportIdHelp: 'Inviaci questo identificativo se hai bisogno di aiuto con il tuo account.', copySupportId: 'Copia', copiedSupportId: 'Copiato', trial: 'Prova Team per 30 giorni', trialDescription: 'Crea gruppi, invita giocatori e molto altro', detailsDescription: 'Personalizza come ti vedono gli altri giocatori.', legacy: 'Il tuo account è precedente ai nuovi profili. Completa questi dati una sola volta per creare il tuo.', nickLocked: 'Al momento il nickname non può essere modificato.', saved: 'Modifiche salvate.', saving: 'Salvataggio…', save: 'Salva modifiche', create: 'Crea il mio profilo', saveError: 'Impossibile salvare i dati. Controlla il nickname e riprova.' },
    groups: { title: 'I miei gruppi', loading: 'Caricamento dei gruppi…', noSession: 'Nessuna sessione attiva', loadError: 'Impossibile caricare i gruppi', deleteError: 'Impossibile eliminare il gruppo', premium: 'Passa a Premium', premiumActive: 'Premium attivo', empty: 'Non hai ancora creato nessun gruppo', delete: 'Elimina gruppo', accessCode: 'Codice di accesso', copyCode: 'Copia codice', copied: 'Copiato', copy: 'Copia', select: 'Seleziona gruppo', created: 'Creato il {{date}}', deleteConfirm: 'Vuoi davvero eliminare questo gruppo? Questa azione non può essere annullata.' },
    roundSetup: { quick: 'Partita rapida', manager: 'Gestione partite e punteggi', express: 'Modalità Express', remaining: 'Ti restano {{remaining}} partite su {{total}} in questa modalità.', played: 'Hai giocato {{count}} partite', groupCode: 'Codice del gruppo', leaveGroup: 'Esci dal gruppo', leave: 'Esci', shareCode: 'Condividi questo codice per consentire agli altri di partecipare alle partite del gruppo:', group: 'Gruppo: {{name}}', joinTitle: 'Unisciti a una partita con un codice', joinDescription: 'Hai un codice di accesso? Usalo per unirti a una partita e modificare i punteggi.', enterCode: 'Inserisci codice', newRound: 'Nuova partita', selectCourse: 'Seleziona un campo', coursePlaceholder: '-- Seleziona un campo --', holes: 'Numero di buche', holesCount: '{{count}} buche', handicap: 'Calcolo dell’handicap', withSlope: 'Con Slope', withoutSlope: 'Senza Slope', selectTee: 'Seleziona tee', gameMode: 'Modalità di gioco', matchHelp: '2 giocatori. Si vince per buca, non a punti.', sindicatoHelp: '3 giocatori. 6 punti per buca: 4/2/0, 3/3/0 o 4/1/1.', pairsHelp: '2 coppie di 2 giocatori (4 in totale).', create: 'Crea partita', active: 'Partite attive', myRound: 'La mia partita', activeDescription: 'Modifica le partite e segui in tempo reale i punteggi di tutte le partite attive.', myRoundDescription: 'Apri la partita rapida attiva e riprendi da dove eri rimasto.', viewRound: 'Visualizza partita', statistics: 'Statistiche', viewStatistics: 'Visualizza statistiche', statsAvailable: 'Consulta premi e statistiche dello storico partite.', statsEmpty: 'Non ci sono partite completate o archiviate da mostrare.', points: 'Punti di gioco', viewPoints: 'Visualizza punti', errors: { courses: 'Impossibile caricare i campi da golf', expressLimit: 'Hai raggiunto il limite di 4 partite del piano Express.', active: 'Hai una partita in corso. Completala o eliminala prima di crearne un’altra.', archive: 'Hai una partita completata da archiviare. Archiviala in Le mie partite prima di crearne un’altra.', selectCourse: 'Seleziona un campo.', create: 'Impossibile creare la partita', pin: 'PIN errato. Riprova.' } },
  } },
} as const;

void i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: initialLanguage,
    fallbackLng: 'es',
    supportedLngs: [...supportedLanguages],
    load: 'languageOnly',
    interpolation: { escapeValue: false },
    react: { useSuspense: false },
  });

i18n.on('languageChanged', (language) => {
  const resolvedLanguage = supportedLanguages.includes(language as SupportedLanguage) ? language : 'es';
  window.localStorage.setItem(LANGUAGE_STORAGE_KEY, resolvedLanguage);
  document.documentElement.lang = resolvedLanguage;
});

document.documentElement.lang = i18n.resolvedLanguage || 'es';

export default i18n;
